<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-V26TDURT" name="Test.RegisterTest" tests="6" failures="0" timestamp="12 Feb 2017 08:57:53 GMT" time="26.680" errors="1">
  <testcase name="enteringInvalidemailid" time="1.145" classname="Test.RegisterTest"/>
  <testcase name="invalidMobienumber" time="1.164" classname="Test.RegisterTest"/>
  <testcase name="missingFullname" time="1.084" classname="Test.RegisterTest"/>
  <testcase name="empptyregister" time="0.969" classname="Test.RegisterTest">
    <error type="java.lang.AssertionError" message="expected [Full Name is required.
e-Mail is required.
Mobile Number is required.] but found [Full Name is required.e-Mail is required.Mobile Number is required.]">
      <![CDATA[java.lang.AssertionError: expected [Full Name is required.
e-Mail is required.
Mobile Number is required.] but found [Full Name is required.e-Mail is required.Mobile Number is required.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Test.RegisterTest.empptyregister(RegisterTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- empptyregister -->
  <testcase name="missingMobileno" time="1.001" classname="Test.RegisterTest"/>
  <testcase name="existingEmailId" time="21.317" classname="Test.RegisterTest"/>
</testsuite> <!-- Test.RegisterTest -->
